#!/usr/bin/env python3
"""
Generate the full LaTeX document including all source files and theoretical content.

This script scans all generated .tex files and theoretical content directories,
generating icpclib-full.tex with everything included.

Usage: python3 generate_full.py
"""
import sys
from pathlib import Path

try:
    import yaml
    HAS_YAML = True
except ImportError:
    HAS_YAML = False

SCRIPT_DIR = Path(__file__).parent.resolve()
CONFIG_FILE = SCRIPT_DIR / "finals.yaml"
OUTPUT_FILE = SCRIPT_DIR / "icpclib-full.tex"
GENERATED_DIR = SCRIPT_DIR / "generated"
THEORETICAL_CONTENT_DIR = SCRIPT_DIR / "theoretical" / "content"

# Chapter display names (matches generate_tex.py CHAPTER_TITLES)
CHAPTER_NAMES = {
    'structures': 'Data Structures',
    'graphs': 'Graph Algorithms',
    'math': 'Mathematics',
    'strings': 'String Algorithms',
    'dp': 'Dynamic Programming',
    'geometry': 'Computational Geometry',
    'extra': 'Extra (Templates and Utilities)',
}

# Preferred chapter order
CHAPTER_ORDER = ['structures', 'graphs', 'math', 'strings', 'dp', 'geometry', 'extra']


def strip_numeric_prefix(name: str) -> str:
    """Strip leading 'NN_' numeric prefix from a directory/file name."""
    parts = name.split('_', 1)
    if len(parts) == 2 and parts[0].isdigit():
        return parts[1]
    return name


def slug_to_display_name(slug: str) -> str:
    """Convert an underscore slug to a Title Case display name."""
    return ' '.join(word.capitalize() for word in slug.split('_'))


def load_team_info() -> dict:
    """Load team info from finals.yaml if available."""
    if not HAS_YAML or not CONFIG_FILE.exists():
        return {}
    with CONFIG_FILE.open('r', encoding='utf-8') as f:
        config = yaml.safe_load(f)
    return config.get('team', {})


def generate_code_chapters_tex() -> str:
    """Generate LaTeX for all code chapters by scanning generated/ directory."""
    if not GENERATED_DIR.exists():
        print(f"Error: generated/ not found. Run generate_tex.py first.", file=sys.stderr)
        sys.exit(1)

    categories = [d.name for d in sorted(GENERATED_DIR.iterdir()) if d.is_dir()]

    def sort_key(cat):
        try:
            return CHAPTER_ORDER.index(cat)
        except ValueError:
            return len(CHAPTER_ORDER)

    categories.sort(key=sort_key)

    lines = [r'\etocdepthtag.toc{code}', '']

    for category in categories:
        cat_dir = GENERATED_DIR / category
        tex_files = sorted(f.name for f in cat_dir.iterdir() if f.suffix == '.tex')
        if not tex_files:
            continue

        display_name = CHAPTER_NAMES.get(category, category.title())
        lines.append(f'% === {category.upper()} ===')
        lines.append(f'\\section{{{display_name}}}')
        lines.append('')

        for tex_file in tex_files:
            lines.append(f'\\input{{generated/{category}/{tex_file}}}')

        lines.append('')

    return '\n'.join(lines)


def generate_theoretical_tex() -> str:
    """Generate LaTeX for all theoretical content."""
    if not THEORETICAL_CONTENT_DIR.exists():
        return ''

    lines = [
        '',
        r'% === THEORETICAL GUIDE ===',
        r'\etocdepthtag.toc{theoretical}',
        r'\renewcommand{\theHsection}{th.\arabic{section}}',
        r'\setcounter{section}{0}',
        '',
    ]

    for chapter_dir in sorted(THEORETICAL_CONTENT_DIR.iterdir()):
        if not chapter_dir.is_dir() or chapter_dir.name.startswith('.'):
            continue

        slug = strip_numeric_prefix(chapter_dir.name)
        display_name = slug_to_display_name(slug)

        sub_files = sorted(f for f in chapter_dir.iterdir() if f.is_file() and f.suffix == '.tex')
        if not sub_files:
            continue

        lines.append(f'\\section{{{display_name}}}')
        lines.append('')

        for sub_file in sub_files:
            rel = f'theoretical/content/{chapter_dir.name}/{sub_file.stem}'
            lines.append(f'\\input{{{rel}}}')

        lines.append('')

    return '\n'.join(lines)


def generate_full_tex(team: dict) -> str:
    """Generate the complete full LaTeX document."""
    teamname = team.get('name', 'ICPC Team')
    university = team.get('university', '')
    members = team.get('members', [])
    author = ', '.join(str(m) for m in members) if members else teamname

    lines = []

    lines.append(r'% ICPC Library - Full Edition')
    lines.append(r'% Auto-generated by generate_full.py - DO NOT EDIT DIRECTLY')
    lines.append(r'%')
    lines.append(r'')
    lines.append(r'\documentclass[9pt,a4paper,landscape]{extarticle}')
    lines.append(r'\usepackage{icpclibpkg}')
    lines.append(r'')
    lines.append(f'\\teamname{{{teamname}}}')
    lines.append(f'\\universityname{{{university}}}')
    lines.append(f'\\author{{{author}}}')
    lines.append(r'\date{\today}')
    lines.append(r'')
    lines.append(r'\begin{document}')
    lines.append(r'')

    # Cover page
    lines.append(r'% Cover page')
    lines.append(r'\makecover')
    lines.append(r'\thispagestyle{fancy}')
    lines.append(r'')
    lines.append(r'\vspace{2mm}')
    lines.append(r'')

    # Two TOC blocks
    lines.append(r'% Table of Contents')
    lines.append(r'\begingroup')
    lines.append(r'\footnotesize')
    lines.append(r'\setlength{\columnsep}{3mm}')
    lines.append(r'\etocsettocstyle{}{}')
    lines.append(r'')
    lines.append(r'% Code Contents (4 columns)')
    lines.append(r'{\small\bfseries Code Contents}\par\vspace{0.5mm}')
    lines.append(r'\etocsettagdepth{code}{subsection}')
    lines.append(r'\etocsettagdepth{theoretical}{none}')
    lines.append(r'\begin{multicols}{4}')
    lines.append(r'\tableofcontents')
    lines.append(r'\end{multicols}')
    lines.append(r'')
    lines.append(r'\vspace{1mm}')
    lines.append(r'')
    lines.append(r'% Theoretical Contents (4 columns)')
    lines.append(r'{\small\bfseries Theoretical Contents}\par\vspace{0.5mm}')
    lines.append(r'\etocsettagdepth{code}{none}')
    lines.append(r'\etocsettagdepth{theoretical}{subsection}')
    lines.append(r'\begin{multicols}{4}')
    lines.append(r'\tableofcontents')
    lines.append(r'\end{multicols}')
    lines.append(r'')
    lines.append(r'\endgroup')
    lines.append(r'')
    lines.append(r'\vspace{2mm}')
    lines.append(r'\hrule')
    lines.append(r'\vspace{2mm}')
    lines.append(r'')

    # Main content
    lines.append(r'% Main content')
    lines.append(r'\begin{multicols*}{3}')
    lines.append(r'')

    lines.append(generate_code_chapters_tex())
    lines.append(generate_theoretical_tex())

    lines.append(r'\end{multicols*}')
    lines.append(r'')
    lines.append(r'\end{document}')

    return '\n'.join(lines)


def main():
    print("=== Generating full LaTeX document ===")

    team = load_team_info()
    if team:
        print(f"Team: {team.get('name', '')}")

    total_code = 0
    if GENERATED_DIR.exists():
        for cat_dir in GENERATED_DIR.iterdir():
            if cat_dir.is_dir():
                total_code += sum(1 for f in cat_dir.iterdir() if f.suffix == '.tex')

    total_th = 0
    if THEORETICAL_CONTENT_DIR.exists():
        for ch_dir in THEORETICAL_CONTENT_DIR.iterdir():
            if ch_dir.is_dir():
                total_th += sum(1 for f in ch_dir.iterdir() if f.suffix == '.tex')

    print(f"Code files: {total_code}, Theoretical subsections: {total_th}")

    latex = generate_full_tex(team)

    with OUTPUT_FILE.open('w', encoding='utf-8') as f:
        f.write(latex)

    print(f"Generated: {OUTPUT_FILE}")


if __name__ == '__main__':
    main()
