#!/usr/bin/env python3
"""
Generate the full LaTeX document including all source files and theoretical content.

Scans all generated .tex files and theoretical content directories,
generating icpclib-full.tex with everything included.

Usage: python3 generate_full.py
"""
import sys
from pathlib import Path

from common import (
    SCRIPT_DIR, GENERATED_DIR, THEORETICAL_CONTENT_DIR,
    CHAPTER_NAMES, CHAPTER_ORDER,
    strip_numeric_prefix, slug_to_display_name,
    load_team_info, render_document,
)

OUTPUT_FILE = SCRIPT_DIR / "icpclib-full.tex"


def generate_code_body() -> str:
    """Generate LaTeX for all code chapters by scanning generated/ directory."""
    if not GENERATED_DIR.exists():
        print("Error: generated/ not found. Run generate_tex.py first.", file=sys.stderr)
        sys.exit(1)

    categories = [d.name for d in sorted(GENERATED_DIR.iterdir()) if d.is_dir()]

    def sort_key(cat):
        try:
            return CHAPTER_ORDER.index(cat)
        except ValueError:
            return len(CHAPTER_ORDER)

    categories.sort(key=sort_key)

    lines = [r'\etocdepthtag.toc{code}', '']

    for category in categories:
        cat_dir = GENERATED_DIR / category
        tex_files = sorted(f.name for f in cat_dir.iterdir() if f.suffix == '.tex')
        if not tex_files:
            continue

        display_name = CHAPTER_NAMES.get(category, category.title())
        lines.append(f'% === {category.upper()} ===')
        lines.append(f'\\section{{{display_name}}}')
        lines.append('')

        for tex_file in tex_files:
            lines.append(f'\\input{{generated/{category}/{tex_file}}}')

        lines.append('')

    return '\n'.join(lines)


def generate_theoretical_body() -> str:
    """Generate LaTeX for all theoretical content."""
    if not THEORETICAL_CONTENT_DIR.exists():
        return ''

    lines = [
        '',
        r'% === THEORETICAL GUIDE ===',
        r'\etocdepthtag.toc{theoretical}',
        r'\renewcommand{\theHsection}{th.\arabic{section}}',
        r'\setcounter{section}{0}',
        '',
    ]

    for chapter_dir in sorted(THEORETICAL_CONTENT_DIR.iterdir()):
        if not chapter_dir.is_dir() or chapter_dir.name.startswith('.'):
            continue

        slug = strip_numeric_prefix(chapter_dir.name)
        display_name = slug_to_display_name(slug)

        sub_files = sorted(f for f in chapter_dir.iterdir() if f.is_file() and f.suffix == '.tex')
        if not sub_files:
            continue

        lines.append(f'\\section{{{display_name}}}')
        lines.append('')

        for sub_file in sub_files:
            rel = f'theoretical/content/{chapter_dir.name}/{sub_file.stem}'
            lines.append(f'\\input{{{rel}}}')

        lines.append('')

    return '\n'.join(lines)


def main():
    print("=== Generating full LaTeX document ===")

    team = load_team_info()
    if team:
        print(f"Team: {team.get('name', '')}")

    total_code = 0
    if GENERATED_DIR.exists():
        for cat_dir in GENERATED_DIR.iterdir():
            if cat_dir.is_dir():
                total_code += sum(1 for f in cat_dir.iterdir() if f.suffix == '.tex')

    total_th = 0
    if THEORETICAL_CONTENT_DIR.exists():
        for ch_dir in THEORETICAL_CONTENT_DIR.iterdir():
            if ch_dir.is_dir():
                total_th += sum(1 for f in ch_dir.iterdir() if f.suffix == '.tex')

    print(f"Code files: {total_code}, Theoretical subsections: {total_th}")

    latex = render_document(
        team=team,
        code_body=generate_code_body(),
        theoretical_body=generate_theoretical_body(),
        edition="Full",
        comment="Auto-generated by generate_full.py - DO NOT EDIT DIRECTLY",
    )

    with OUTPUT_FILE.open('w', encoding='utf-8') as f:
        f.write(latex)

    print(f"Generated: {OUTPUT_FILE}")


if __name__ == '__main__':
    main()
